theme: jekyll-theme-minimal
title : nDP Repository
author : Andrés González Santa Cruz,
email : gonzalez.santacruz.andres@gmail.com
description: |
navbar:
  right:
    - text: "Home"
      href: index.html