*clear all
cap noi use "E:\Mi unidad\Alvacast\SISTRAT 2022 (github)\fiscalia_mariel_oct_2022_match_SENDA.dta", clear
cap noi label variable hash_key "Hash (ID)"
cap noi label variable edad_al_ing_fmt "Age (admission to treatment)"
cap noi label variable edad_ini_cons "Age of Onset of Substance Use"
cap noi label variable dias_treat_imp_sin_na_1 "Days in treatment"
cap noi label variable sex "Sex"
cap noi label variable escolaridad_rec "Educational Attainment"
cap noi label variable sus_principal_mod "Primary Substance (admission to treatment)"
cap noi label variable freq_cons_sus_prin "Substance use frequency (primary substance)"
cap noi label variable compromiso_biopsicosocial "Bio-psychosocial status"
cap noi label variable tenencia_de_la_vivienda_mod "Housing situation (tenure status of households)"
cap noi label variable dg_cie_10_rec "Comorbidity (ICD-10)"
cap noi label variable dg_trs_cons_sus_or "SUD Severity (Dependence status)"
cap noi label variable macrozona "Macro administrative Chilean zone"
cap noi label variable policonsumo "Co-occurring SUD"
cap noi label variable tr_modality "Treatment Modality"
cap noi label variable tipo_centro "Center ID"
cap noi label variable condicion_ocupacional_cor "Occupational Status Corrected"
cap noi label variable origen_ingreso_mod "Motive of Admission to Treatment"
cap noi label variable numero_de_hijos_mod "Number of Children "
cap noi label variable n_prev_off "Pre-treatment Criminality (Dich.)"
cap noi label variable n_off_vio "Violent crime, Pre-treatment Criminality"
cap noi label variable n_off_acq "Acquisitive crime, Pre-treatment Criminality"
cap noi label variable n_off_sud "Substance use-related crime, Pre-treatment Criminality"
cap noi label variable n_off_oth "Other crime, Pre-treatment Criminality"
cap noi label variable age_offending_imp "Age when the offense was committed"
cap noi label variable edad_al_egres_imp "Age at discharge (mod)"
cap noi label variable fech_nac_rec "Corrected date of birth"
cap noi label variable motivodeegreso_mod_imp_rec "Baseline treatment status"
cap noi label variable fech_ing_num_1 "Date of admission"
cap noi label variable fech_egres_imp "Date of discharge"
cap noi label variable cut_com_del "Binned comission date"
cap noi label variable cut_fec_nac "Binned birth date"
cap noi label variable offender_d ""
cap noi save "E:\Mi unidad\Alvacast\SISTRAT 2022 (github)\fiscalia_mariel_oct_2022_match_SENDA.dta", replace
cap noi save "E:\Mi unidad\Alvacast\SISTRAT 2022 (github)\fiscalia_mariel_oct_2022_match_SENDA.dta", replace
