*clear all
cap noi use "E:\Mi unidad\Alvacast\SISTRAT 2022 (github)\fiscalia_mariel_feb_2023_match_SENDA.dta", clear
cap noi label variable hash_key "Hash (ID)"
cap noi label variable edad_al_ing_1 "Age (admission to treatment)"
cap noi label variable edad_ini_cons "Age of Onset of Substance Use"
cap noi label variable dias_treat_imp_sin_na_1 "Days in treatment"
cap noi label variable sex "Sex"
cap noi label variable escolaridad_rec ""
cap noi label variable sus_principal_mod ""
cap noi label variable freq_cons_sus_prin ""
cap noi label variable compromiso_biopsicosocial "Bio-psychosocial status"
cap noi label variable tenencia_de_la_vivienda_mod ""
cap noi label variable dg_cie_10_rec "Comorbidity (ICD-10)"
cap noi label variable dg_trs_cons_sus_or "SUD Severity (Dependence status)"
cap noi label variable macrozona ""
cap noi label variable policonsumo "Co-occurring SUD"
cap noi label variable tr_modality "Treatment Modality"
cap noi label variable tipo_centro "Type of Center"
cap noi label variable condicion_ocupacional_cor "Occupational Status Corrected"
cap noi label variable origen_ingreso_mod "Motive of Admission to Treatment"
cap noi label variable numero_de_hijos_mod "Number of Children "
cap noi label variable n_prev_off "Pre-treatment Criminality (Dich.)"
cap noi label variable n_off_vio ""
cap noi label variable n_off_acq ""
cap noi label variable n_off_sud ""
cap noi label variable n_off_oth "Other crime, Pre-treatment Criminality"
cap noi label variable age_offending_imp ""
cap noi label variable edad_al_egres_imp "Age at discharge (mod)"
cap noi label variable fech_nac_rec "Corrected date of birth"
cap noi label variable motivodeegreso_mod_imp_rec ""
cap noi label variable fech_ing_num_1 "Date of admission"
cap noi label variable fech_egres_imp "Date of discharge"
cap noi label variable cut_com_del "Binned comission date"
cap noi label variable cut_fec_nac "Binned birth date"
cap noi label variable offender_d ""
cap noi label variable comuna_residencia_cod_rec ""
cap noi label variable porc_pobr ""
cap noi label variable Clasificación ""
cap noi label variable tipo_de_vivienda_mod ""
cap noi label variable via_adm_sus_prin_act ""
cap noi label variable cat_ocupacional_corr ""
cap noi label variable clas_centers_r ""
cap noi label variable clas_r ""
cap noi save "E:\Mi unidad\Alvacast\SISTRAT 2022 (github)\fiscalia_mariel_feb_2023_match_SENDA.dta", replace
cap noi save "E:\Mi unidad\Alvacast\SISTRAT 2022 (github)\fiscalia_mariel_feb_2023_match_SENDA.dta", replace
