---
name: "repositorio_dsp_ags"
title: "nDP Repository"
lang: es-ES
subject: R Markdown
author:
  - first_name: "Andrés"
    last_name: "González-Santa Cruz"
    url: https://github.com/nDP
    affiliation: Technical Staff of Núcleo Milenio de Drogas; Ph.D. student, School of Public Health, Universidad de Chile
    affiliation_url: 
    email: gonzalez.santacruz.andres@gmail.com
    orcid_id: 0000-0002-5166-9121
  - first_name: "Mariel"
    last_name: "Mateo Piñones"
    url: https://github.com/nDP
    affiliation: Ph.D. student, Griffith University, Australia
    affiliation_url: 
    email: mariel.mateopinones@griffithuni.edu.au
    orcid_id: 0000-0002-9607-7541
description: |
 A small part of the research done and available in https://www.nucleondp.cl/ 
base_url: https://beta.rstudioconnect.com/content/3776/
creative_commons: CC BY
output: 
  distill::distill_article:
    theme: theme.css
---

- [Presentation at nDP Extended Meeting](pres_2022jun.html)

- [Chilean prosecutor’s office Data merge (Step 1)](Fiscalia_merge.html)

- [Chilean prosecutor’s office Data merge (Step 2)](Fiscalia_merge2.html)

- [Chilean prosecutor’s office Data merge (Step 3.1)](Fiscalia_merge31.html)

- [Chilean prosecutor’s office Data merge (Step 3.2)](Fiscalia_merge32.html)

- [Chilean prosecutor’s office Data merge (Step 4)](Fiscalia_merge4.html)

- [Chilean prosecutor’s office Data merge (Step 5)](Fiscalia_merge5.html)

**Assessing the impact of substance use treatment for preventing criminal justice system contact in Chile**

- [Descriptive glimpse and initial analysis ](analisis_mariel_nov_2022_stata.html)

- [Descriptive glimpse and initial analysis (Imprisonment only)](analisis_mariel_nov_2022_stata_pris.html)

- [Main analyses](analisis_mariel_feb_2023_stata.html)

- [Main analyses (Imprisonment only)](analisis_mariel_feb_2023_stata_pris.html)

- [Main analyses of Imputed Data](analisis_mariel_feb_2023_stata_m1.html)

- [Main analyses of Imputed Data (Imprisonment only)](analisis_mariel_feb_2023_stata_pris_m1.html)

- [Main analyses of Imputed Data (including diagnoses in-study)](analisis_mariel_feb_2023_stata_m2.html)

- [Main analyses of Imputed Data (Imprisonment only, including diagnoses in-study)](analisis_mariel_feb_2023_stata_pris_m2.html)

- [Summary tables & Sensitivity Analyses](res_intram_feb_2023_stata.html)

- [Poster (idea)](pres_dic_22.html)

**Poly-substance use, treatment completion, and contact with the justice system: a multistate analysis of treatments for substance use disorders between 2010-2019, Chile**

- [Material for SER 2023 (step 0: aalen-johansen, selection of IPWeights & schoenfeld residuals)](an_ser_2023_step_0.html)

- [Material for SER 2023 (step 1: parametric partitioned survival models & multistate models)](an_ser_2023_step_1.html)

- [Material for SER 2023 (step 2: parametric partitioned survival models & multistate models)](an_ser_2023_step_2.html)

**Short commentary: Self-reported offending vs. official records: estimating the gap in the Chilean context**

- [step 1](top_vs_po.html)

- [Poster (idea)](pres_2023mar.html)
